// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.0
// source: web/v1/web.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebServer_GetSettings_FullMethodName = "/file.v1.WebServer/GetSettings"
)

// WebServerClient is the client API for WebServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebServerClient interface {
	GetSettings(ctx context.Context, in *SettingRequest, opts ...grpc.CallOption) (*SettingReply, error)
}

type webServerClient struct {
	cc grpc.ClientConnInterface
}

func NewWebServerClient(cc grpc.ClientConnInterface) WebServerClient {
	return &webServerClient{cc}
}

func (c *webServerClient) GetSettings(ctx context.Context, in *SettingRequest, opts ...grpc.CallOption) (*SettingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingReply)
	err := c.cc.Invoke(ctx, WebServer_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebServerServer is the server API for WebServer service.
// All implementations must embed UnimplementedWebServerServer
// for forward compatibility.
type WebServerServer interface {
	GetSettings(context.Context, *SettingRequest) (*SettingReply, error)
	mustEmbedUnimplementedWebServerServer()
}

// UnimplementedWebServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebServerServer struct{}

func (UnimplementedWebServerServer) GetSettings(context.Context, *SettingRequest) (*SettingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedWebServerServer) mustEmbedUnimplementedWebServerServer() {}
func (UnimplementedWebServerServer) testEmbeddedByValue()                   {}

// UnsafeWebServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebServerServer will
// result in compilation errors.
type UnsafeWebServerServer interface {
	mustEmbedUnimplementedWebServerServer()
}

func RegisterWebServerServer(s grpc.ServiceRegistrar, srv WebServerServer) {
	// If the following call pancis, it indicates UnimplementedWebServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebServer_ServiceDesc, srv)
}

func _WebServer_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServerServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebServer_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServerServer).GetSettings(ctx, req.(*SettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebServer_ServiceDesc is the grpc.ServiceDesc for WebServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "file.v1.WebServer",
	HandlerType: (*WebServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSettings",
			Handler:    _WebServer_GetSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "web/v1/web.proto",
}
