// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.2
// - protoc             v5.27.0
// source: web/v1/web.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationWebServerGetSettings = "/file.v1.WebServer/GetSettings"

type WebServerHTTPServer interface {
	GetSettings(context.Context, *SettingRequest) (*SettingReply, error)
}

func RegisterWebServerHTTPServer(s *http.Server, srv WebServerHTTPServer) {
	r := s.Route("/")
	r.GET("/web/{account_id}", _WebServer_GetSettings0_HTTP_Handler(srv))
}

func _WebServer_GetSettings0_HTTP_Handler(srv WebServerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SettingRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWebServerGetSettings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSettings(ctx, req.(*SettingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SettingReply)
		return ctx.Result(200, reply)
	}
}

type WebServerHTTPClient interface {
	GetSettings(ctx context.Context, req *SettingRequest, opts ...http.CallOption) (rsp *SettingReply, err error)
}

type WebServerHTTPClientImpl struct {
	cc *http.Client
}

func NewWebServerHTTPClient(client *http.Client) WebServerHTTPClient {
	return &WebServerHTTPClientImpl{client}
}

func (c *WebServerHTTPClientImpl) GetSettings(ctx context.Context, in *SettingRequest, opts ...http.CallOption) (*SettingReply, error) {
	var out SettingReply
	pattern := "/web/{account_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWebServerGetSettings))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
