// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.0
// source: healthcheck/v1/healthcheck.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthcheckServer_LivenessProbe_FullMethodName  = "/healthcheck.v1.HealthcheckServer/LivenessProbe"
	HealthcheckServer_ReadinessProbe_FullMethodName = "/healthcheck.v1.HealthcheckServer/ReadinessProbe"
)

// HealthcheckServerClient is the client API for HealthcheckServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthcheckServerClient interface {
	LivenessProbe(ctx context.Context, in *LivenessRequest, opts ...grpc.CallOption) (*LivenessReply, error)
	ReadinessProbe(ctx context.Context, in *ReadinessRequest, opts ...grpc.CallOption) (*ReadinessReply, error)
}

type healthcheckServerClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthcheckServerClient(cc grpc.ClientConnInterface) HealthcheckServerClient {
	return &healthcheckServerClient{cc}
}

func (c *healthcheckServerClient) LivenessProbe(ctx context.Context, in *LivenessRequest, opts ...grpc.CallOption) (*LivenessReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LivenessReply)
	err := c.cc.Invoke(ctx, HealthcheckServer_LivenessProbe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthcheckServerClient) ReadinessProbe(ctx context.Context, in *ReadinessRequest, opts ...grpc.CallOption) (*ReadinessReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadinessReply)
	err := c.cc.Invoke(ctx, HealthcheckServer_ReadinessProbe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthcheckServerServer is the server API for HealthcheckServer service.
// All implementations must embed UnimplementedHealthcheckServerServer
// for forward compatibility.
type HealthcheckServerServer interface {
	LivenessProbe(context.Context, *LivenessRequest) (*LivenessReply, error)
	ReadinessProbe(context.Context, *ReadinessRequest) (*ReadinessReply, error)
	mustEmbedUnimplementedHealthcheckServerServer()
}

// UnimplementedHealthcheckServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthcheckServerServer struct{}

func (UnimplementedHealthcheckServerServer) LivenessProbe(context.Context, *LivenessRequest) (*LivenessReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LivenessProbe not implemented")
}
func (UnimplementedHealthcheckServerServer) ReadinessProbe(context.Context, *ReadinessRequest) (*ReadinessReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadinessProbe not implemented")
}
func (UnimplementedHealthcheckServerServer) mustEmbedUnimplementedHealthcheckServerServer() {}
func (UnimplementedHealthcheckServerServer) testEmbeddedByValue()                           {}

// UnsafeHealthcheckServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthcheckServerServer will
// result in compilation errors.
type UnsafeHealthcheckServerServer interface {
	mustEmbedUnimplementedHealthcheckServerServer()
}

func RegisterHealthcheckServerServer(s grpc.ServiceRegistrar, srv HealthcheckServerServer) {
	// If the following call pancis, it indicates UnimplementedHealthcheckServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthcheckServer_ServiceDesc, srv)
}

func _HealthcheckServer_LivenessProbe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LivenessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthcheckServerServer).LivenessProbe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthcheckServer_LivenessProbe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthcheckServerServer).LivenessProbe(ctx, req.(*LivenessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthcheckServer_ReadinessProbe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthcheckServerServer).ReadinessProbe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthcheckServer_ReadinessProbe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthcheckServerServer).ReadinessProbe(ctx, req.(*ReadinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthcheckServer_ServiceDesc is the grpc.ServiceDesc for HealthcheckServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthcheckServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "healthcheck.v1.HealthcheckServer",
	HandlerType: (*HealthcheckServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LivenessProbe",
			Handler:    _HealthcheckServer_LivenessProbe_Handler,
		},
		{
			MethodName: "ReadinessProbe",
			Handler:    _HealthcheckServer_ReadinessProbe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "healthcheck/v1/healthcheck.proto",
}
